### ISSUE TITLE
Cleanup "configs" section

### ISSUE THREAD

**Issue by edg2s** [wikimedia/eslint-plugin-jquery#16]
The "deprecated" config appears to contain all rules from the original repo, and not actually deprecated methods: http://api.jquery.com/category/deprecated/ many of which are missing.

The "slim" config contains a small list of rules, with no explanation.

**Comment by edg2s** [comment]
For deprecations we should be able to group the them by version number, then cascade in all the previous versions:

deprecated-3.3 = rules-3.3 + deprecated-3.0
deprecated-3.0 = rules-3.0 + deprecated-1.10
...
deprecated-1.3 = rules-1.3

**Comment by edg2s** [comment]
For reference the syntax for using configs from plugins is:

`"extends": "plugin:jquery/deprecated"`

which is helpfully not well documented

**Comment by edg2s** [comment]
Deprecations in short form:

### 1.3
$.boxModel (removed 1.8, use feat det)
$.browser (removed 1.9, use feat det)

### 1.7
deferred.isRejected()/isResolved (removed 1.8, use state())
$().die()/$().live() (removed 1.9, use off/on())
$.sub() (removed 1.9)
$().selector (removed 3.0)

### 1.8
$().andSelf (removed 3.0, use $.addBack)
deferred.pipe() (use .then)
$().error (removed 3.0, use on)
$().load (removed 3.0, use on)
$().size (removed 3.0, use length prop)
$().toggle( fn, fn ) (removed 1.9, use on)
$().unload (removed 3.0, use on)

### 1.9
$.support (use Modernizr?)

### 1.10
$().context (removed 3.0)

### 3.0
$().bind (use $.on)
$().delegate (use $.on)
$.fx.interval
$.parseJSON (JSON.parse)
$.unique (use $.uniqueSort)

### 3.3
$.isFunction (use typeof)
$.isWindow

**Comment by jdforrester** [comment]
Once we do this let's release wmf.2.
